# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/stradale/Documents/main_files/TEKNOFEST_MCU_Project/TEKNOFEST_MCU_Project.runs/synth_1/fpga_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param simulator.questaInstallPath /usr/altera/questa_fse/bin
set_param general.usePosixSpawnForFork 1
set_param simulator.modelsimInstallPath /usr/altera/questa_fse/bin
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/stradale/Documents/main_files/TEKNOFEST_MCU_Project/TEKNOFEST_MCU_Project.cache/wt [current_project]
set_property parent.project_path /home/stradale/Documents/main_files/TEKNOFEST_MCU_Project/TEKNOFEST_MCU_Project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/stradale/.Xilinx/Vivado/2025.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo /home/stradale/Documents/main_files/TEKNOFEST_MCU_Project/TEKNOFEST_MCU_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/stradale/Documents/main_files/main_codes/rtl/include/CPU/axi_typedef.svh
  /home/stradale/Documents/main_files/main_codes/rtl/include/CPU/obi_typedef.svh
  /home/stradale/Documents/main_files/main_codes/rtl/include/CPU/registers.svh
}
set_property file_type "Verilog Header" [get_files /home/stradale/Documents/main_files/main_codes/rtl/include/CPU/axi_typedef.svh]
set_property file_type "Verilog Header" [get_files /home/stradale/Documents/main_files/main_codes/rtl/include/CPU/obi_typedef.svh]
set_property file_type "Verilog Header" [get_files /home/stradale/Documents/main_files/main_codes/rtl/include/CPU/registers.svh]
read_verilog -library xil_defaultlib -sv {
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Interconnect/Interconnect/AXI4_Interconnect.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Peripherals/GPIO/GPIO_AXI4_Lite.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Peripherals/I2C/I2C_Master_AXI4_Lite.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Interconnect/Instruction_Splitter/Instruction_Splitter.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Peripherals/QSPI/QSPI_Master_AXI4_Lite.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Peripherals/Timer/Timer_AXI4_Lite.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Top_Module/Top_module.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Peripherals/UART_GU/UART_GU_AXI4-Lite.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Peripherals/UART_YZ/UART_YZ_AXI4-Lite.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/openhw_obi_to_axi/axi_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/bizim_kodlar/axi_req_rsp_ports.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Memory/Boot_ROM_AXI4-Lite_Wrapper/boot_bram_axi_ctrl.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Memory/Boot_ROM_def/boot_rom_def.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Memory/RAM_def/bram_def.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_aligner.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/include/cv32e40p_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_alu.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_alu_div.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/include/cv32e40p_apu_core_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_apu_disp.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_clock_gate.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_compressed_decoder.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_controller.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_core.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_cs_registers.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/include/cv32e40p_fpu_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_decoder.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_ex_stage.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_ff_one.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_fifo.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/fpnew/fpnew_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_fp_wrapper.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_hwloop_regs.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_id_stage.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_if_stage.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_int_controller.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_load_store_unit.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_mult.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_obi_interface.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/openhw_obi_to_axi/obi_pkg.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/bizim_kodlar/obi_req_rsp_ports.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/bizim_kodlar/cv32e40p_obi_to_axi_wrapper.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_popcnt.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_prefetch_buffer.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_prefetch_controller.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_register_file_ff.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_sleep_unit.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/cv32e40p_top.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Memory/Data_RAM_AXI4-Lite_Wrapper/data_bram_axi_ctrl.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/pulp_platform_common_cells/include/common_cells/src/fifo_v3.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/fpnew/fpnew_opgroup_block.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/fpnew/fpnew_opgroup_fmt_slice.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/fpnew/fpnew_top.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/Memory/Instrurction_RAM_AXI4-Lite_Wrapper/instr_bram_axi_ctrl.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/pulp_platform_common_cells/src/lzc.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/openhw_obi_to_axi/obi_to_axi.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/CPU/cv32e40p_rtl/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv
  /home/stradale/Documents/main_files/main_codes/rtl/desgin_sources/fpga_top.sv
}
read_ip -quiet /home/stradale/Documents/main_files/main_codes/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/stradale/Documents/TEKNOFEST_MCU_Project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/stradale/Documents/TEKNOFEST_MCU_Project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/stradale/Documents/TEKNOFEST_MCU_Project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/stradale/Documents/main_files/main_codes/constraint/basys3_soc.xdc
set_property used_in_implementation false [get_files /home/stradale/Documents/main_files/main_codes/constraint/basys3_soc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga_top -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
