# Generated by scripts/recharacterize_sram.py; do not hand-edit.
word_size = 32
num_words = 256
write_size = 8
num_banks = 1
words_per_row = 2
num_rw_ports = 1
num_r_ports = 1
num_w_ports = 0

tech_name = "sky130"
output_name = "sky130_sram_1kbyte_1rw1r_32x256_8"
output_path = '/home/luxyxp/Documents/mainfiles/asic/run/lib_characterization/pilot_3x3_probe_4p0ns/TT_1p8V_25C/output/'
openram_temp = '/home/luxyxp/Documents/mainfiles/asic/run/lib_characterization/pilot_3x3_probe_4p0ns/TT_1p8V_25C/'
existing_sram_width = 479.78
existing_sram_height = 397.5

analytical_delay = False
spice_name = "ngspice"
use_conda = False
keep_temp = True
check_lvsdrc = False

use_specified_corners = [('TT', 1.8, 25)]
only_use_config_corners = True
process_corners = ['TT']
supply_voltages = [1.8]
temperatures = [25]
slew_scales = [0.25, 1, 8]
load_scales = [0.25, 1, 4]

# The matching PDK TT Liberty reports a 1.791 ns minimum period.  Starting at
# 1 ns exercises normal feasibility doubling to 2 ns, then the independent
# minimum-period search, without paying for the upstream 10 ns starting point.
# Unknown 2 KiB PVTs get a looser functional/probe guard.
existing_sram_initial_period = 4.0
existing_sram_functional_guard_period = 4.0
existing_sram_feasibility_only = True
