-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Sat May  9 17:16:57 2026
-- Host        : Stradale running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Users/deniz/Documents/TEKNOFEST_Modules/birlestirme_denemesi/birlestirme_denemesi.gen/sources_1/bd/design_1/ip/design_1_Instr_Splitter_0_0/design_1_Instr_Splitter_0_0_stub.vhdl
-- Design      : design_1_Instr_Splitter_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7a35tcpg236-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_Instr_Splitter_0_0 is
  Port ( 
    clk_i : in STD_LOGIC;
    rst_n : in STD_LOGIC;
    axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_awvalid : in STD_LOGIC;
    axi_awready : out STD_LOGIC;
    axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_wlast : in STD_LOGIC;
    axi_wvalid : in STD_LOGIC;
    axi_wready : out STD_LOGIC;
    axi_bready : in STD_LOGIC;
    axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_bvalid : out STD_LOGIC;
    axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_arvalid : in STD_LOGIC;
    axi_arready : out STD_LOGIC;
    axi_rready : in STD_LOGIC;
    axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_rlast : out STD_LOGIC;
    axi_rvalid : out STD_LOGIC;
    i_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    i_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    i_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    i_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    i_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    i_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    i_awvalid : out STD_LOGIC;
    i_awready : in STD_LOGIC;
    i_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    i_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    i_wlast : out STD_LOGIC;
    i_wvalid : out STD_LOGIC;
    i_wready : in STD_LOGIC;
    i_bready : out STD_LOGIC;
    i_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    i_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    i_bvalid : in STD_LOGIC;
    i_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    i_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    i_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    i_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    i_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    i_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    i_arvalid : out STD_LOGIC;
    i_arready : in STD_LOGIC;
    i_rready : out STD_LOGIC;
    i_rid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    i_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    i_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    i_rlast : in STD_LOGIC;
    i_rvalid : in STD_LOGIC;
    b_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    b_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    b_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    b_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    b_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    b_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    b_awvalid : out STD_LOGIC;
    b_awready : in STD_LOGIC;
    b_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    b_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    b_wlast : out STD_LOGIC;
    b_wvalid : out STD_LOGIC;
    b_wready : in STD_LOGIC;
    b_bready : out STD_LOGIC;
    b_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    b_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    b_bvalid : in STD_LOGIC;
    b_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    b_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    b_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    b_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    b_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    b_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    b_arvalid : out STD_LOGIC;
    b_arready : in STD_LOGIC;
    b_rready : out STD_LOGIC;
    b_rid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    b_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    b_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    b_rlast : in STD_LOGIC;
    b_rvalid : in STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_Instr_Splitter_0_0 : entity is "design_1_Instr_Splitter_0_0,Instr_Splitter,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_Instr_Splitter_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of design_1_Instr_Splitter_0_0 : entity is "package_project";
end design_1_Instr_Splitter_0_0;

architecture stub of design_1_Instr_Splitter_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "clk_i,rst_n,axi_awid[3:0],axi_awaddr[31:0],axi_awlen[7:0],axi_awsize[2:0],axi_awburst[1:0],axi_awprot[2:0],axi_awvalid,axi_awready,axi_wdata[31:0],axi_wstrb[3:0],axi_wlast,axi_wvalid,axi_wready,axi_bready,axi_bid[3:0],axi_bresp[1:0],axi_bvalid,axi_arid[3:0],axi_araddr[31:0],axi_arlen[7:0],axi_arsize[2:0],axi_arburst[1:0],axi_arprot[2:0],axi_arvalid,axi_arready,axi_rready,axi_rid[3:0],axi_rdata[31:0],axi_rresp[1:0],axi_rlast,axi_rvalid,i_awid[3:0],i_awaddr[31:0],i_awlen[7:0],i_awsize[2:0],i_awburst[1:0],i_awprot[2:0],i_awvalid,i_awready,i_wdata[31:0],i_wstrb[3:0],i_wlast,i_wvalid,i_wready,i_bready,i_bid[3:0],i_bresp[1:0],i_bvalid,i_arid[3:0],i_araddr[31:0],i_arlen[7:0],i_arsize[2:0],i_arburst[1:0],i_arprot[2:0],i_arvalid,i_arready,i_rready,i_rid[3:0],i_rdata[31:0],i_rresp[1:0],i_rlast,i_rvalid,b_awid[3:0],b_awaddr[31:0],b_awlen[7:0],b_awsize[2:0],b_awburst[1:0],b_awprot[2:0],b_awvalid,b_awready,b_wdata[31:0],b_wstrb[3:0],b_wlast,b_wvalid,b_wready,b_bready,b_bid[3:0],b_bresp[1:0],b_bvalid,b_arid[3:0],b_araddr[31:0],b_arlen[7:0],b_arsize[2:0],b_arburst[1:0],b_arprot[2:0],b_arvalid,b_arready,b_rready,b_rid[3:0],b_rdata[31:0],b_rresp[1:0],b_rlast,b_rvalid";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of clk_i : signal is "xilinx.com:signal:clock:1.0 clk_i CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of clk_i : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of clk_i : signal is "XIL_INTERFACENAME clk_i, FREQ_TOLERANCE_HZ 0, ASSOCIATED_BUSIF b:i:axi, FREQ_HZ 50000000, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rst_n : signal is "xilinx.com:signal:reset:1.0 rst_n RST";
  attribute X_INTERFACE_MODE of rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of rst_n : signal is "XIL_INTERFACENAME rst_n, POLARITY ACTIVE_LOW, ASSOCIATED_RESET rst_n, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_awid : signal is "xilinx.com:interface:aximm:1.0 axi AWID";
  attribute X_INTERFACE_MODE of axi_awid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of axi_awid : signal is "XIL_INTERFACENAME axi, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 50000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi AWADDR";
  attribute X_INTERFACE_INFO of axi_awlen : signal is "xilinx.com:interface:aximm:1.0 axi AWLEN";
  attribute X_INTERFACE_INFO of axi_awsize : signal is "xilinx.com:interface:aximm:1.0 axi AWSIZE";
  attribute X_INTERFACE_INFO of axi_awburst : signal is "xilinx.com:interface:aximm:1.0 axi AWBURST";
  attribute X_INTERFACE_INFO of axi_awprot : signal is "xilinx.com:interface:aximm:1.0 axi AWPROT";
  attribute X_INTERFACE_INFO of axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi AWVALID";
  attribute X_INTERFACE_INFO of axi_awready : signal is "xilinx.com:interface:aximm:1.0 axi AWREADY";
  attribute X_INTERFACE_INFO of axi_wdata : signal is "xilinx.com:interface:aximm:1.0 axi WDATA";
  attribute X_INTERFACE_INFO of axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 axi WSTRB";
  attribute X_INTERFACE_INFO of axi_wlast : signal is "xilinx.com:interface:aximm:1.0 axi WLAST";
  attribute X_INTERFACE_INFO of axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi WVALID";
  attribute X_INTERFACE_INFO of axi_wready : signal is "xilinx.com:interface:aximm:1.0 axi WREADY";
  attribute X_INTERFACE_INFO of axi_bready : signal is "xilinx.com:interface:aximm:1.0 axi BREADY";
  attribute X_INTERFACE_INFO of axi_bid : signal is "xilinx.com:interface:aximm:1.0 axi BID";
  attribute X_INTERFACE_INFO of axi_bresp : signal is "xilinx.com:interface:aximm:1.0 axi BRESP";
  attribute X_INTERFACE_INFO of axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi BVALID";
  attribute X_INTERFACE_INFO of axi_arid : signal is "xilinx.com:interface:aximm:1.0 axi ARID";
  attribute X_INTERFACE_INFO of axi_araddr : signal is "xilinx.com:interface:aximm:1.0 axi ARADDR";
  attribute X_INTERFACE_INFO of axi_arlen : signal is "xilinx.com:interface:aximm:1.0 axi ARLEN";
  attribute X_INTERFACE_INFO of axi_arsize : signal is "xilinx.com:interface:aximm:1.0 axi ARSIZE";
  attribute X_INTERFACE_INFO of axi_arburst : signal is "xilinx.com:interface:aximm:1.0 axi ARBURST";
  attribute X_INTERFACE_INFO of axi_arprot : signal is "xilinx.com:interface:aximm:1.0 axi ARPROT";
  attribute X_INTERFACE_INFO of axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi ARVALID";
  attribute X_INTERFACE_INFO of axi_arready : signal is "xilinx.com:interface:aximm:1.0 axi ARREADY";
  attribute X_INTERFACE_INFO of axi_rready : signal is "xilinx.com:interface:aximm:1.0 axi RREADY";
  attribute X_INTERFACE_INFO of axi_rid : signal is "xilinx.com:interface:aximm:1.0 axi RID";
  attribute X_INTERFACE_INFO of axi_rdata : signal is "xilinx.com:interface:aximm:1.0 axi RDATA";
  attribute X_INTERFACE_INFO of axi_rresp : signal is "xilinx.com:interface:aximm:1.0 axi RRESP";
  attribute X_INTERFACE_INFO of axi_rlast : signal is "xilinx.com:interface:aximm:1.0 axi RLAST";
  attribute X_INTERFACE_INFO of axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi RVALID";
  attribute X_INTERFACE_INFO of i_awid : signal is "xilinx.com:interface:aximm:1.0 i AWID";
  attribute X_INTERFACE_MODE of i_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of i_awid : signal is "XIL_INTERFACENAME i, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 50000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of i_awaddr : signal is "xilinx.com:interface:aximm:1.0 i AWADDR";
  attribute X_INTERFACE_INFO of i_awlen : signal is "xilinx.com:interface:aximm:1.0 i AWLEN";
  attribute X_INTERFACE_INFO of i_awsize : signal is "xilinx.com:interface:aximm:1.0 i AWSIZE";
  attribute X_INTERFACE_INFO of i_awburst : signal is "xilinx.com:interface:aximm:1.0 i AWBURST";
  attribute X_INTERFACE_INFO of i_awprot : signal is "xilinx.com:interface:aximm:1.0 i AWPROT";
  attribute X_INTERFACE_INFO of i_awvalid : signal is "xilinx.com:interface:aximm:1.0 i AWVALID";
  attribute X_INTERFACE_INFO of i_awready : signal is "xilinx.com:interface:aximm:1.0 i AWREADY";
  attribute X_INTERFACE_INFO of i_wdata : signal is "xilinx.com:interface:aximm:1.0 i WDATA";
  attribute X_INTERFACE_INFO of i_wstrb : signal is "xilinx.com:interface:aximm:1.0 i WSTRB";
  attribute X_INTERFACE_INFO of i_wlast : signal is "xilinx.com:interface:aximm:1.0 i WLAST";
  attribute X_INTERFACE_INFO of i_wvalid : signal is "xilinx.com:interface:aximm:1.0 i WVALID";
  attribute X_INTERFACE_INFO of i_wready : signal is "xilinx.com:interface:aximm:1.0 i WREADY";
  attribute X_INTERFACE_INFO of i_bready : signal is "xilinx.com:interface:aximm:1.0 i BREADY";
  attribute X_INTERFACE_INFO of i_bid : signal is "xilinx.com:interface:aximm:1.0 i BID";
  attribute X_INTERFACE_INFO of i_bresp : signal is "xilinx.com:interface:aximm:1.0 i BRESP";
  attribute X_INTERFACE_INFO of i_bvalid : signal is "xilinx.com:interface:aximm:1.0 i BVALID";
  attribute X_INTERFACE_INFO of i_arid : signal is "xilinx.com:interface:aximm:1.0 i ARID";
  attribute X_INTERFACE_INFO of i_araddr : signal is "xilinx.com:interface:aximm:1.0 i ARADDR";
  attribute X_INTERFACE_INFO of i_arlen : signal is "xilinx.com:interface:aximm:1.0 i ARLEN";
  attribute X_INTERFACE_INFO of i_arsize : signal is "xilinx.com:interface:aximm:1.0 i ARSIZE";
  attribute X_INTERFACE_INFO of i_arburst : signal is "xilinx.com:interface:aximm:1.0 i ARBURST";
  attribute X_INTERFACE_INFO of i_arprot : signal is "xilinx.com:interface:aximm:1.0 i ARPROT";
  attribute X_INTERFACE_INFO of i_arvalid : signal is "xilinx.com:interface:aximm:1.0 i ARVALID";
  attribute X_INTERFACE_INFO of i_arready : signal is "xilinx.com:interface:aximm:1.0 i ARREADY";
  attribute X_INTERFACE_INFO of i_rready : signal is "xilinx.com:interface:aximm:1.0 i RREADY";
  attribute X_INTERFACE_INFO of i_rid : signal is "xilinx.com:interface:aximm:1.0 i RID";
  attribute X_INTERFACE_INFO of i_rdata : signal is "xilinx.com:interface:aximm:1.0 i RDATA";
  attribute X_INTERFACE_INFO of i_rresp : signal is "xilinx.com:interface:aximm:1.0 i RRESP";
  attribute X_INTERFACE_INFO of i_rlast : signal is "xilinx.com:interface:aximm:1.0 i RLAST";
  attribute X_INTERFACE_INFO of i_rvalid : signal is "xilinx.com:interface:aximm:1.0 i RVALID";
  attribute X_INTERFACE_INFO of b_awid : signal is "xilinx.com:interface:aximm:1.0 b AWID";
  attribute X_INTERFACE_MODE of b_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of b_awid : signal is "XIL_INTERFACENAME b, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 50000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of b_awaddr : signal is "xilinx.com:interface:aximm:1.0 b AWADDR";
  attribute X_INTERFACE_INFO of b_awlen : signal is "xilinx.com:interface:aximm:1.0 b AWLEN";
  attribute X_INTERFACE_INFO of b_awsize : signal is "xilinx.com:interface:aximm:1.0 b AWSIZE";
  attribute X_INTERFACE_INFO of b_awburst : signal is "xilinx.com:interface:aximm:1.0 b AWBURST";
  attribute X_INTERFACE_INFO of b_awprot : signal is "xilinx.com:interface:aximm:1.0 b AWPROT";
  attribute X_INTERFACE_INFO of b_awvalid : signal is "xilinx.com:interface:aximm:1.0 b AWVALID";
  attribute X_INTERFACE_INFO of b_awready : signal is "xilinx.com:interface:aximm:1.0 b AWREADY";
  attribute X_INTERFACE_INFO of b_wdata : signal is "xilinx.com:interface:aximm:1.0 b WDATA";
  attribute X_INTERFACE_INFO of b_wstrb : signal is "xilinx.com:interface:aximm:1.0 b WSTRB";
  attribute X_INTERFACE_INFO of b_wlast : signal is "xilinx.com:interface:aximm:1.0 b WLAST";
  attribute X_INTERFACE_INFO of b_wvalid : signal is "xilinx.com:interface:aximm:1.0 b WVALID";
  attribute X_INTERFACE_INFO of b_wready : signal is "xilinx.com:interface:aximm:1.0 b WREADY";
  attribute X_INTERFACE_INFO of b_bready : signal is "xilinx.com:interface:aximm:1.0 b BREADY";
  attribute X_INTERFACE_INFO of b_bid : signal is "xilinx.com:interface:aximm:1.0 b BID";
  attribute X_INTERFACE_INFO of b_bresp : signal is "xilinx.com:interface:aximm:1.0 b BRESP";
  attribute X_INTERFACE_INFO of b_bvalid : signal is "xilinx.com:interface:aximm:1.0 b BVALID";
  attribute X_INTERFACE_INFO of b_arid : signal is "xilinx.com:interface:aximm:1.0 b ARID";
  attribute X_INTERFACE_INFO of b_araddr : signal is "xilinx.com:interface:aximm:1.0 b ARADDR";
  attribute X_INTERFACE_INFO of b_arlen : signal is "xilinx.com:interface:aximm:1.0 b ARLEN";
  attribute X_INTERFACE_INFO of b_arsize : signal is "xilinx.com:interface:aximm:1.0 b ARSIZE";
  attribute X_INTERFACE_INFO of b_arburst : signal is "xilinx.com:interface:aximm:1.0 b ARBURST";
  attribute X_INTERFACE_INFO of b_arprot : signal is "xilinx.com:interface:aximm:1.0 b ARPROT";
  attribute X_INTERFACE_INFO of b_arvalid : signal is "xilinx.com:interface:aximm:1.0 b ARVALID";
  attribute X_INTERFACE_INFO of b_arready : signal is "xilinx.com:interface:aximm:1.0 b ARREADY";
  attribute X_INTERFACE_INFO of b_rready : signal is "xilinx.com:interface:aximm:1.0 b RREADY";
  attribute X_INTERFACE_INFO of b_rid : signal is "xilinx.com:interface:aximm:1.0 b RID";
  attribute X_INTERFACE_INFO of b_rdata : signal is "xilinx.com:interface:aximm:1.0 b RDATA";
  attribute X_INTERFACE_INFO of b_rresp : signal is "xilinx.com:interface:aximm:1.0 b RRESP";
  attribute X_INTERFACE_INFO of b_rlast : signal is "xilinx.com:interface:aximm:1.0 b RLAST";
  attribute X_INTERFACE_INFO of b_rvalid : signal is "xilinx.com:interface:aximm:1.0 b RVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "Instr_Splitter,Vivado 2025.2";
begin
end;
