-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Sun May 10 17:03:17 2026
-- Host        : Stradale running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Users/deniz/Documents/TEKNOFEST_Modules/birlestirme_denemesi/birlestirme_denemesi.gen/sources_1/bd/design_1/ip/design_1_AXI4_Interconnect_0_0/design_1_AXI4_Interconnect_0_0_stub.vhdl
-- Design      : design_1_AXI4_Interconnect_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7a35tcpg236-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_AXI4_Interconnect_0_0 is
  Port ( 
    clk_i : in STD_LOGIC;
    rst_ni : in STD_LOGIC;
    axi_s0_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_s0_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_s0_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_s0_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_s0_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_s0_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_s0_awvalid : in STD_LOGIC;
    axi_s0_awready : out STD_LOGIC;
    axi_s0_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_s0_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_s0_wlast : in STD_LOGIC;
    axi_s0_wvalid : in STD_LOGIC;
    axi_s0_wready : out STD_LOGIC;
    axi_s0_bready : in STD_LOGIC;
    axi_s0_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_s0_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_s0_bvalid : out STD_LOGIC;
    axi_s0_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_s0_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_s0_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_s0_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_s0_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_s0_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_s0_arvalid : in STD_LOGIC;
    axi_s0_arready : out STD_LOGIC;
    axi_s0_rready : in STD_LOGIC;
    axi_s0_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_s0_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_s0_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_s0_rlast : out STD_LOGIC;
    axi_s0_rvalid : out STD_LOGIC;
    axi_m0_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m0_awvalid : out STD_LOGIC;
    axi_m0_awready : in STD_LOGIC;
    axi_m0_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m0_wvalid : out STD_LOGIC;
    axi_m0_wready : in STD_LOGIC;
    axi_m0_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m0_bvalid : in STD_LOGIC;
    axi_m0_bready : out STD_LOGIC;
    axi_m0_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m0_arvalid : out STD_LOGIC;
    axi_m0_arready : in STD_LOGIC;
    axi_m0_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m0_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m0_rvalid : in STD_LOGIC;
    axi_m0_rready : out STD_LOGIC;
    axi_m1_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m1_awvalid : out STD_LOGIC;
    axi_m1_awready : in STD_LOGIC;
    axi_m1_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m1_wvalid : out STD_LOGIC;
    axi_m1_wready : in STD_LOGIC;
    axi_m1_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m1_bvalid : in STD_LOGIC;
    axi_m1_bready : out STD_LOGIC;
    axi_m1_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m1_arvalid : out STD_LOGIC;
    axi_m1_arready : in STD_LOGIC;
    axi_m1_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m1_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m1_rvalid : in STD_LOGIC;
    axi_m1_rready : out STD_LOGIC;
    axi_m2_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m2_awvalid : out STD_LOGIC;
    axi_m2_awready : in STD_LOGIC;
    axi_m2_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m2_wvalid : out STD_LOGIC;
    axi_m2_wready : in STD_LOGIC;
    axi_m2_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m2_bvalid : in STD_LOGIC;
    axi_m2_bready : out STD_LOGIC;
    axi_m2_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m2_arvalid : out STD_LOGIC;
    axi_m2_arready : in STD_LOGIC;
    axi_m2_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m2_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m2_rvalid : in STD_LOGIC;
    axi_m2_rready : out STD_LOGIC;
    axi_m3_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m3_awvalid : out STD_LOGIC;
    axi_m3_awready : in STD_LOGIC;
    axi_m3_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m3_wvalid : out STD_LOGIC;
    axi_m3_wready : in STD_LOGIC;
    axi_m3_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m3_bvalid : in STD_LOGIC;
    axi_m3_bready : out STD_LOGIC;
    axi_m3_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m3_arvalid : out STD_LOGIC;
    axi_m3_arready : in STD_LOGIC;
    axi_m3_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m3_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m3_rvalid : in STD_LOGIC;
    axi_m3_rready : out STD_LOGIC;
    axi_m4_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m4_awvalid : out STD_LOGIC;
    axi_m4_awready : in STD_LOGIC;
    axi_m4_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m4_wvalid : out STD_LOGIC;
    axi_m4_wready : in STD_LOGIC;
    axi_m4_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m4_bvalid : in STD_LOGIC;
    axi_m4_bready : out STD_LOGIC;
    axi_m4_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m4_arvalid : out STD_LOGIC;
    axi_m4_arready : in STD_LOGIC;
    axi_m4_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m4_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m4_rvalid : in STD_LOGIC;
    axi_m4_rready : out STD_LOGIC;
    axi_m4_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m4_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_m4_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m4_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m4_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m4_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m4_wlast : out STD_LOGIC;
    axi_m4_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m4_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_m4_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m4_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m4_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m4_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m4_rlast : in STD_LOGIC;
    axi_m4_rid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m5_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m5_awvalid : out STD_LOGIC;
    axi_m5_awready : in STD_LOGIC;
    axi_m5_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m5_wvalid : out STD_LOGIC;
    axi_m5_wready : in STD_LOGIC;
    axi_m5_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m5_bvalid : in STD_LOGIC;
    axi_m5_bready : out STD_LOGIC;
    axi_m5_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m5_arvalid : out STD_LOGIC;
    axi_m5_arready : in STD_LOGIC;
    axi_m5_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_m5_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m5_rvalid : in STD_LOGIC;
    axi_m5_rready : out STD_LOGIC;
    axi_m5_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m5_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_m5_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m5_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m5_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m5_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m5_wlast : out STD_LOGIC;
    axi_m5_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m5_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    axi_m5_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m5_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    axi_m5_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    axi_m5_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_m5_rlast : in STD_LOGIC;
    axi_m5_rid : in STD_LOGIC_VECTOR ( 3 downto 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_AXI4_Interconnect_0_0 : entity is "design_1_AXI4_Interconnect_0_0,AXI4_Interconnect,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_AXI4_Interconnect_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of design_1_AXI4_Interconnect_0_0 : entity is "package_project";
end design_1_AXI4_Interconnect_0_0;

architecture stub of design_1_AXI4_Interconnect_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "clk_i,rst_ni,axi_s0_awid[3:0],axi_s0_awaddr[31:0],axi_s0_awlen[7:0],axi_s0_awsize[2:0],axi_s0_awburst[1:0],axi_s0_awprot[2:0],axi_s0_awvalid,axi_s0_awready,axi_s0_wdata[31:0],axi_s0_wstrb[3:0],axi_s0_wlast,axi_s0_wvalid,axi_s0_wready,axi_s0_bready,axi_s0_bid[3:0],axi_s0_bresp[1:0],axi_s0_bvalid,axi_s0_arid[3:0],axi_s0_araddr[31:0],axi_s0_arlen[7:0],axi_s0_arsize[2:0],axi_s0_arburst[1:0],axi_s0_arprot[2:0],axi_s0_arvalid,axi_s0_arready,axi_s0_rready,axi_s0_rid[3:0],axi_s0_rdata[31:0],axi_s0_rresp[1:0],axi_s0_rlast,axi_s0_rvalid,axi_m0_awaddr[31:0],axi_m0_awvalid,axi_m0_awready,axi_m0_wdata[31:0],axi_m0_wvalid,axi_m0_wready,axi_m0_bresp[1:0],axi_m0_bvalid,axi_m0_bready,axi_m0_araddr[31:0],axi_m0_arvalid,axi_m0_arready,axi_m0_rdata[31:0],axi_m0_rresp[1:0],axi_m0_rvalid,axi_m0_rready,axi_m1_awaddr[31:0],axi_m1_awvalid,axi_m1_awready,axi_m1_wdata[31:0],axi_m1_wvalid,axi_m1_wready,axi_m1_bresp[1:0],axi_m1_bvalid,axi_m1_bready,axi_m1_araddr[31:0],axi_m1_arvalid,axi_m1_arready,axi_m1_rdata[31:0],axi_m1_rresp[1:0],axi_m1_rvalid,axi_m1_rready,axi_m2_awaddr[31:0],axi_m2_awvalid,axi_m2_awready,axi_m2_wdata[31:0],axi_m2_wvalid,axi_m2_wready,axi_m2_bresp[1:0],axi_m2_bvalid,axi_m2_bready,axi_m2_araddr[31:0],axi_m2_arvalid,axi_m2_arready,axi_m2_rdata[31:0],axi_m2_rresp[1:0],axi_m2_rvalid,axi_m2_rready,axi_m3_awaddr[31:0],axi_m3_awvalid,axi_m3_awready,axi_m3_wdata[31:0],axi_m3_wvalid,axi_m3_wready,axi_m3_bresp[1:0],axi_m3_bvalid,axi_m3_bready,axi_m3_araddr[31:0],axi_m3_arvalid,axi_m3_arready,axi_m3_rdata[31:0],axi_m3_rresp[1:0],axi_m3_rvalid,axi_m3_rready,axi_m4_awaddr[31:0],axi_m4_awvalid,axi_m4_awready,axi_m4_wdata[31:0],axi_m4_wvalid,axi_m4_wready,axi_m4_bresp[1:0],axi_m4_bvalid,axi_m4_bready,axi_m4_araddr[31:0],axi_m4_arvalid,axi_m4_arready,axi_m4_rdata[31:0],axi_m4_rresp[1:0],axi_m4_rvalid,axi_m4_rready,axi_m4_awid[3:0],axi_m4_awlen[7:0],axi_m4_awsize[2:0],axi_m4_awburst[1:0],axi_m4_awprot[2:0],axi_m4_wstrb[3:0],axi_m4_wlast,axi_m4_arid[3:0],axi_m4_arlen[7:0],axi_m4_arsize[2:0],axi_m4_arburst[1:0],axi_m4_arprot[2:0],axi_m4_bid[3:0],axi_m4_rlast,axi_m4_rid[3:0],axi_m5_awaddr[31:0],axi_m5_awvalid,axi_m5_awready,axi_m5_wdata[31:0],axi_m5_wvalid,axi_m5_wready,axi_m5_bresp[1:0],axi_m5_bvalid,axi_m5_bready,axi_m5_araddr[31:0],axi_m5_arvalid,axi_m5_arready,axi_m5_rdata[31:0],axi_m5_rresp[1:0],axi_m5_rvalid,axi_m5_rready,axi_m5_awid[3:0],axi_m5_awlen[7:0],axi_m5_awsize[2:0],axi_m5_awburst[1:0],axi_m5_awprot[2:0],axi_m5_wstrb[3:0],axi_m5_wlast,axi_m5_arid[3:0],axi_m5_arlen[7:0],axi_m5_arsize[2:0],axi_m5_arburst[1:0],axi_m5_arprot[2:0],axi_m5_bid[3:0],axi_m5_rlast,axi_m5_rid[3:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of clk_i : signal is "xilinx.com:signal:clock:1.0 clk_i CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of clk_i : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of clk_i : signal is "XIL_INTERFACENAME clk_i, FREQ_TOLERANCE_HZ 0, ASSOCIATED_BUSIF axi_m0:axi_m1:axi_m2:axi_m3:axi_m4:axi_m5:axi_s0, FREQ_HZ 50000000, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rst_ni : signal is "xilinx.com:signal:reset:1.0 rst_ni RST";
  attribute X_INTERFACE_MODE of rst_ni : signal is "slave";
  attribute X_INTERFACE_PARAMETER of rst_ni : signal is "XIL_INTERFACENAME rst_ni, POLARITY ACTIVE_LOW, ASSOCIATED_RESET rst_ni, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_s0_awid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWID";
  attribute X_INTERFACE_MODE of axi_s0_awid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of axi_s0_awid : signal is "XIL_INTERFACENAME axi_s0, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 50000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_s0_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWADDR";
  attribute X_INTERFACE_INFO of axi_s0_awlen : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWLEN";
  attribute X_INTERFACE_INFO of axi_s0_awsize : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWSIZE";
  attribute X_INTERFACE_INFO of axi_s0_awburst : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWBURST";
  attribute X_INTERFACE_INFO of axi_s0_awprot : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWPROT";
  attribute X_INTERFACE_INFO of axi_s0_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWVALID";
  attribute X_INTERFACE_INFO of axi_s0_awready : signal is "xilinx.com:interface:aximm:1.0 axi_s0 AWREADY";
  attribute X_INTERFACE_INFO of axi_s0_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_s0 WDATA";
  attribute X_INTERFACE_INFO of axi_s0_wstrb : signal is "xilinx.com:interface:aximm:1.0 axi_s0 WSTRB";
  attribute X_INTERFACE_INFO of axi_s0_wlast : signal is "xilinx.com:interface:aximm:1.0 axi_s0 WLAST";
  attribute X_INTERFACE_INFO of axi_s0_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 WVALID";
  attribute X_INTERFACE_INFO of axi_s0_wready : signal is "xilinx.com:interface:aximm:1.0 axi_s0 WREADY";
  attribute X_INTERFACE_INFO of axi_s0_bready : signal is "xilinx.com:interface:aximm:1.0 axi_s0 BREADY";
  attribute X_INTERFACE_INFO of axi_s0_bid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 BID";
  attribute X_INTERFACE_INFO of axi_s0_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_s0 BRESP";
  attribute X_INTERFACE_INFO of axi_s0_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 BVALID";
  attribute X_INTERFACE_INFO of axi_s0_arid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARID";
  attribute X_INTERFACE_INFO of axi_s0_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARADDR";
  attribute X_INTERFACE_INFO of axi_s0_arlen : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARLEN";
  attribute X_INTERFACE_INFO of axi_s0_arsize : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARSIZE";
  attribute X_INTERFACE_INFO of axi_s0_arburst : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARBURST";
  attribute X_INTERFACE_INFO of axi_s0_arprot : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARPROT";
  attribute X_INTERFACE_INFO of axi_s0_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARVALID";
  attribute X_INTERFACE_INFO of axi_s0_arready : signal is "xilinx.com:interface:aximm:1.0 axi_s0 ARREADY";
  attribute X_INTERFACE_INFO of axi_s0_rready : signal is "xilinx.com:interface:aximm:1.0 axi_s0 RREADY";
  attribute X_INTERFACE_INFO of axi_s0_rid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 RID";
  attribute X_INTERFACE_INFO of axi_s0_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_s0 RDATA";
  attribute X_INTERFACE_INFO of axi_s0_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_s0 RRESP";
  attribute X_INTERFACE_INFO of axi_s0_rlast : signal is "xilinx.com:interface:aximm:1.0 axi_s0 RLAST";
  attribute X_INTERFACE_INFO of axi_s0_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_s0 RVALID";
  attribute X_INTERFACE_INFO of axi_m0_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_m0 AWADDR";
  attribute X_INTERFACE_MODE of axi_m0_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of axi_m0_awaddr : signal is "XIL_INTERFACENAME axi_m0, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_m0_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m0 AWVALID";
  attribute X_INTERFACE_INFO of axi_m0_awready : signal is "xilinx.com:interface:aximm:1.0 axi_m0 AWREADY";
  attribute X_INTERFACE_INFO of axi_m0_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_m0 WDATA";
  attribute X_INTERFACE_INFO of axi_m0_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m0 WVALID";
  attribute X_INTERFACE_INFO of axi_m0_wready : signal is "xilinx.com:interface:aximm:1.0 axi_m0 WREADY";
  attribute X_INTERFACE_INFO of axi_m0_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_m0 BRESP";
  attribute X_INTERFACE_INFO of axi_m0_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m0 BVALID";
  attribute X_INTERFACE_INFO of axi_m0_bready : signal is "xilinx.com:interface:aximm:1.0 axi_m0 BREADY";
  attribute X_INTERFACE_INFO of axi_m0_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_m0 ARADDR";
  attribute X_INTERFACE_INFO of axi_m0_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m0 ARVALID";
  attribute X_INTERFACE_INFO of axi_m0_arready : signal is "xilinx.com:interface:aximm:1.0 axi_m0 ARREADY";
  attribute X_INTERFACE_INFO of axi_m0_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_m0 RDATA";
  attribute X_INTERFACE_INFO of axi_m0_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_m0 RRESP";
  attribute X_INTERFACE_INFO of axi_m0_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m0 RVALID";
  attribute X_INTERFACE_INFO of axi_m0_rready : signal is "xilinx.com:interface:aximm:1.0 axi_m0 RREADY";
  attribute X_INTERFACE_INFO of axi_m1_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_m1 AWADDR";
  attribute X_INTERFACE_MODE of axi_m1_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of axi_m1_awaddr : signal is "XIL_INTERFACENAME axi_m1, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_m1_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m1 AWVALID";
  attribute X_INTERFACE_INFO of axi_m1_awready : signal is "xilinx.com:interface:aximm:1.0 axi_m1 AWREADY";
  attribute X_INTERFACE_INFO of axi_m1_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_m1 WDATA";
  attribute X_INTERFACE_INFO of axi_m1_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m1 WVALID";
  attribute X_INTERFACE_INFO of axi_m1_wready : signal is "xilinx.com:interface:aximm:1.0 axi_m1 WREADY";
  attribute X_INTERFACE_INFO of axi_m1_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_m1 BRESP";
  attribute X_INTERFACE_INFO of axi_m1_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m1 BVALID";
  attribute X_INTERFACE_INFO of axi_m1_bready : signal is "xilinx.com:interface:aximm:1.0 axi_m1 BREADY";
  attribute X_INTERFACE_INFO of axi_m1_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_m1 ARADDR";
  attribute X_INTERFACE_INFO of axi_m1_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m1 ARVALID";
  attribute X_INTERFACE_INFO of axi_m1_arready : signal is "xilinx.com:interface:aximm:1.0 axi_m1 ARREADY";
  attribute X_INTERFACE_INFO of axi_m1_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_m1 RDATA";
  attribute X_INTERFACE_INFO of axi_m1_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_m1 RRESP";
  attribute X_INTERFACE_INFO of axi_m1_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m1 RVALID";
  attribute X_INTERFACE_INFO of axi_m1_rready : signal is "xilinx.com:interface:aximm:1.0 axi_m1 RREADY";
  attribute X_INTERFACE_INFO of axi_m2_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_m2 AWADDR";
  attribute X_INTERFACE_MODE of axi_m2_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of axi_m2_awaddr : signal is "XIL_INTERFACENAME axi_m2, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_m2_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m2 AWVALID";
  attribute X_INTERFACE_INFO of axi_m2_awready : signal is "xilinx.com:interface:aximm:1.0 axi_m2 AWREADY";
  attribute X_INTERFACE_INFO of axi_m2_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_m2 WDATA";
  attribute X_INTERFACE_INFO of axi_m2_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m2 WVALID";
  attribute X_INTERFACE_INFO of axi_m2_wready : signal is "xilinx.com:interface:aximm:1.0 axi_m2 WREADY";
  attribute X_INTERFACE_INFO of axi_m2_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_m2 BRESP";
  attribute X_INTERFACE_INFO of axi_m2_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m2 BVALID";
  attribute X_INTERFACE_INFO of axi_m2_bready : signal is "xilinx.com:interface:aximm:1.0 axi_m2 BREADY";
  attribute X_INTERFACE_INFO of axi_m2_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_m2 ARADDR";
  attribute X_INTERFACE_INFO of axi_m2_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m2 ARVALID";
  attribute X_INTERFACE_INFO of axi_m2_arready : signal is "xilinx.com:interface:aximm:1.0 axi_m2 ARREADY";
  attribute X_INTERFACE_INFO of axi_m2_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_m2 RDATA";
  attribute X_INTERFACE_INFO of axi_m2_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_m2 RRESP";
  attribute X_INTERFACE_INFO of axi_m2_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m2 RVALID";
  attribute X_INTERFACE_INFO of axi_m2_rready : signal is "xilinx.com:interface:aximm:1.0 axi_m2 RREADY";
  attribute X_INTERFACE_INFO of axi_m3_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_m3 AWADDR";
  attribute X_INTERFACE_MODE of axi_m3_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of axi_m3_awaddr : signal is "XIL_INTERFACENAME axi_m3, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_m3_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m3 AWVALID";
  attribute X_INTERFACE_INFO of axi_m3_awready : signal is "xilinx.com:interface:aximm:1.0 axi_m3 AWREADY";
  attribute X_INTERFACE_INFO of axi_m3_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_m3 WDATA";
  attribute X_INTERFACE_INFO of axi_m3_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m3 WVALID";
  attribute X_INTERFACE_INFO of axi_m3_wready : signal is "xilinx.com:interface:aximm:1.0 axi_m3 WREADY";
  attribute X_INTERFACE_INFO of axi_m3_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_m3 BRESP";
  attribute X_INTERFACE_INFO of axi_m3_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m3 BVALID";
  attribute X_INTERFACE_INFO of axi_m3_bready : signal is "xilinx.com:interface:aximm:1.0 axi_m3 BREADY";
  attribute X_INTERFACE_INFO of axi_m3_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_m3 ARADDR";
  attribute X_INTERFACE_INFO of axi_m3_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m3 ARVALID";
  attribute X_INTERFACE_INFO of axi_m3_arready : signal is "xilinx.com:interface:aximm:1.0 axi_m3 ARREADY";
  attribute X_INTERFACE_INFO of axi_m3_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_m3 RDATA";
  attribute X_INTERFACE_INFO of axi_m3_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_m3 RRESP";
  attribute X_INTERFACE_INFO of axi_m3_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m3 RVALID";
  attribute X_INTERFACE_INFO of axi_m3_rready : signal is "xilinx.com:interface:aximm:1.0 axi_m3 RREADY";
  attribute X_INTERFACE_INFO of axi_m4_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWADDR";
  attribute X_INTERFACE_MODE of axi_m4_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of axi_m4_awaddr : signal is "XIL_INTERFACENAME axi_m4, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 50000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_m4_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWVALID";
  attribute X_INTERFACE_INFO of axi_m4_awready : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWREADY";
  attribute X_INTERFACE_INFO of axi_m4_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_m4 WDATA";
  attribute X_INTERFACE_INFO of axi_m4_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 WVALID";
  attribute X_INTERFACE_INFO of axi_m4_wready : signal is "xilinx.com:interface:aximm:1.0 axi_m4 WREADY";
  attribute X_INTERFACE_INFO of axi_m4_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_m4 BRESP";
  attribute X_INTERFACE_INFO of axi_m4_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 BVALID";
  attribute X_INTERFACE_INFO of axi_m4_bready : signal is "xilinx.com:interface:aximm:1.0 axi_m4 BREADY";
  attribute X_INTERFACE_INFO of axi_m4_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARADDR";
  attribute X_INTERFACE_INFO of axi_m4_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARVALID";
  attribute X_INTERFACE_INFO of axi_m4_arready : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARREADY";
  attribute X_INTERFACE_INFO of axi_m4_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_m4 RDATA";
  attribute X_INTERFACE_INFO of axi_m4_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_m4 RRESP";
  attribute X_INTERFACE_INFO of axi_m4_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 RVALID";
  attribute X_INTERFACE_INFO of axi_m4_rready : signal is "xilinx.com:interface:aximm:1.0 axi_m4 RREADY";
  attribute X_INTERFACE_INFO of axi_m4_awid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWID";
  attribute X_INTERFACE_INFO of axi_m4_awlen : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWLEN";
  attribute X_INTERFACE_INFO of axi_m4_awsize : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWSIZE";
  attribute X_INTERFACE_INFO of axi_m4_awburst : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWBURST";
  attribute X_INTERFACE_INFO of axi_m4_awprot : signal is "xilinx.com:interface:aximm:1.0 axi_m4 AWPROT";
  attribute X_INTERFACE_INFO of axi_m4_wstrb : signal is "xilinx.com:interface:aximm:1.0 axi_m4 WSTRB";
  attribute X_INTERFACE_INFO of axi_m4_wlast : signal is "xilinx.com:interface:aximm:1.0 axi_m4 WLAST";
  attribute X_INTERFACE_INFO of axi_m4_arid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARID";
  attribute X_INTERFACE_INFO of axi_m4_arlen : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARLEN";
  attribute X_INTERFACE_INFO of axi_m4_arsize : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARSIZE";
  attribute X_INTERFACE_INFO of axi_m4_arburst : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARBURST";
  attribute X_INTERFACE_INFO of axi_m4_arprot : signal is "xilinx.com:interface:aximm:1.0 axi_m4 ARPROT";
  attribute X_INTERFACE_INFO of axi_m4_bid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 BID";
  attribute X_INTERFACE_INFO of axi_m4_rlast : signal is "xilinx.com:interface:aximm:1.0 axi_m4 RLAST";
  attribute X_INTERFACE_INFO of axi_m4_rid : signal is "xilinx.com:interface:aximm:1.0 axi_m4 RID";
  attribute X_INTERFACE_INFO of axi_m5_awaddr : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWADDR";
  attribute X_INTERFACE_MODE of axi_m5_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of axi_m5_awaddr : signal is "XIL_INTERFACENAME axi_m5, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 50000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /clk_wiz_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_m5_awvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWVALID";
  attribute X_INTERFACE_INFO of axi_m5_awready : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWREADY";
  attribute X_INTERFACE_INFO of axi_m5_wdata : signal is "xilinx.com:interface:aximm:1.0 axi_m5 WDATA";
  attribute X_INTERFACE_INFO of axi_m5_wvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 WVALID";
  attribute X_INTERFACE_INFO of axi_m5_wready : signal is "xilinx.com:interface:aximm:1.0 axi_m5 WREADY";
  attribute X_INTERFACE_INFO of axi_m5_bresp : signal is "xilinx.com:interface:aximm:1.0 axi_m5 BRESP";
  attribute X_INTERFACE_INFO of axi_m5_bvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 BVALID";
  attribute X_INTERFACE_INFO of axi_m5_bready : signal is "xilinx.com:interface:aximm:1.0 axi_m5 BREADY";
  attribute X_INTERFACE_INFO of axi_m5_araddr : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARADDR";
  attribute X_INTERFACE_INFO of axi_m5_arvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARVALID";
  attribute X_INTERFACE_INFO of axi_m5_arready : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARREADY";
  attribute X_INTERFACE_INFO of axi_m5_rdata : signal is "xilinx.com:interface:aximm:1.0 axi_m5 RDATA";
  attribute X_INTERFACE_INFO of axi_m5_rresp : signal is "xilinx.com:interface:aximm:1.0 axi_m5 RRESP";
  attribute X_INTERFACE_INFO of axi_m5_rvalid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 RVALID";
  attribute X_INTERFACE_INFO of axi_m5_rready : signal is "xilinx.com:interface:aximm:1.0 axi_m5 RREADY";
  attribute X_INTERFACE_INFO of axi_m5_awid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWID";
  attribute X_INTERFACE_INFO of axi_m5_awlen : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWLEN";
  attribute X_INTERFACE_INFO of axi_m5_awsize : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWSIZE";
  attribute X_INTERFACE_INFO of axi_m5_awburst : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWBURST";
  attribute X_INTERFACE_INFO of axi_m5_awprot : signal is "xilinx.com:interface:aximm:1.0 axi_m5 AWPROT";
  attribute X_INTERFACE_INFO of axi_m5_wstrb : signal is "xilinx.com:interface:aximm:1.0 axi_m5 WSTRB";
  attribute X_INTERFACE_INFO of axi_m5_wlast : signal is "xilinx.com:interface:aximm:1.0 axi_m5 WLAST";
  attribute X_INTERFACE_INFO of axi_m5_arid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARID";
  attribute X_INTERFACE_INFO of axi_m5_arlen : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARLEN";
  attribute X_INTERFACE_INFO of axi_m5_arsize : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARSIZE";
  attribute X_INTERFACE_INFO of axi_m5_arburst : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARBURST";
  attribute X_INTERFACE_INFO of axi_m5_arprot : signal is "xilinx.com:interface:aximm:1.0 axi_m5 ARPROT";
  attribute X_INTERFACE_INFO of axi_m5_bid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 BID";
  attribute X_INTERFACE_INFO of axi_m5_rlast : signal is "xilinx.com:interface:aximm:1.0 axi_m5 RLAST";
  attribute X_INTERFACE_INFO of axi_m5_rid : signal is "xilinx.com:interface:aximm:1.0 axi_m5 RID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "AXI4_Interconnect,Vivado 2025.2";
begin
end;
