## Clock - 100 MHz
set_property PACKAGE_PIN W5  [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk]

## Reset - BTNC (ortadaki buton, active HIGH)
set_property PACKAGE_PIN T18 [get_ports sys_rst_btn]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_btn]

## USB-UART (FT2232HQ üzerinden PC ile konuşur)
set_property PACKAGE_PIN B18 [get_ports UART_GU_rx]
set_property PACKAGE_PIN A18 [get_ports UART_GU_tx]
set_property IOSTANDARD LVCMOS33 [get_ports UART_GU_rx]
set_property IOSTANDARD LVCMOS33 [get_ports UART_GU_tx]

## Switches → GPIO_IDR [15:0]
set_property PACKAGE_PIN V17 [get_ports {GPIO_IDR_pins[0]}]
set_property PACKAGE_PIN V16 [get_ports {GPIO_IDR_pins[1]}]
set_property PACKAGE_PIN W16 [get_ports {GPIO_IDR_pins[2]}]
set_property PACKAGE_PIN W17 [get_ports {GPIO_IDR_pins[3]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO_IDR_pins[4]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO_IDR_pins[5]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO_IDR_pins[6]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO_IDR_pins[7]}]
set_property PACKAGE_PIN V2  [get_ports {GPIO_IDR_pins[8]}]
set_property PACKAGE_PIN T3  [get_ports {GPIO_IDR_pins[9]}]
set_property PACKAGE_PIN T2  [get_ports {GPIO_IDR_pins[10]}]
set_property PACKAGE_PIN R3  [get_ports {GPIO_IDR_pins[11]}]
set_property PACKAGE_PIN W2  [get_ports {GPIO_IDR_pins[12]}]
set_property PACKAGE_PIN U1  [get_ports {GPIO_IDR_pins[13]}]
set_property PACKAGE_PIN T1  [get_ports {GPIO_IDR_pins[14]}]
set_property PACKAGE_PIN R2  [get_ports {GPIO_IDR_pins[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_IDR_pins[*]}]

## LEDs → GPIO_ODR [15:0]
set_property PACKAGE_PIN U16 [get_ports {GPIO_ODR_pins[0]}]
set_property PACKAGE_PIN E19 [get_ports {GPIO_ODR_pins[1]}]
set_property PACKAGE_PIN U19 [get_ports {GPIO_ODR_pins[2]}]
set_property PACKAGE_PIN V19 [get_ports {GPIO_ODR_pins[3]}]
set_property PACKAGE_PIN W18 [get_ports {GPIO_ODR_pins[4]}]
set_property PACKAGE_PIN U15 [get_ports {GPIO_ODR_pins[5]}]
set_property PACKAGE_PIN U14 [get_ports {GPIO_ODR_pins[6]}]
set_property PACKAGE_PIN V14 [get_ports {GPIO_ODR_pins[7]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO_ODR_pins[8]}]
set_property PACKAGE_PIN V3  [get_ports {GPIO_ODR_pins[9]}]
set_property PACKAGE_PIN W3  [get_ports {GPIO_ODR_pins[10]}]
set_property PACKAGE_PIN U3  [get_ports {GPIO_ODR_pins[11]}]
set_property PACKAGE_PIN P3  [get_ports {GPIO_ODR_pins[12]}]
set_property PACKAGE_PIN N3  [get_ports {GPIO_ODR_pins[13]}]
set_property PACKAGE_PIN P1  [get_ports {GPIO_ODR_pins[14]}]
set_property PACKAGE_PIN L1  [get_ports {GPIO_ODR_pins[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_ODR_pins[*]}]

## I2C → PMOD JA
set_property PACKAGE_PIN J1 [get_ports I2C_SCL]
set_property PACKAGE_PIN L2 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDA]

## QSPI → PMOD JB
set_property PACKAGE_PIN A14 [get_ports QSPI_SCLK]
set_property PACKAGE_PIN A16 [get_ports QSPI_CS]
set_property PACKAGE_PIN B15 [get_ports QSPI_IO0]
set_property PACKAGE_PIN B16 [get_ports QSPI_IO1]
set_property PACKAGE_PIN A15 [get_ports QSPI_IO2]
set_property PACKAGE_PIN A17 [get_ports QSPI_IO3]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_*]
