# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kyber_physical.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cv32e40p_obi_to_axi_0_0/design_1_cv32e40p_obi_to_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cv32e40p_obi_to_axi_0_0 || ORIG_REF_NAME==design_1_cv32e40p_obi_to_axi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4_Interconnect_0_0/design_1_AXI4_Interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4_Interconnect_0_0 || ORIG_REF_NAME==design_1_AXI4_Interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_QSPI_Master_AXI4_Lite_0_0/design_1_QSPI_Master_AXI4_Lite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_QSPI_Master_AXI4_Lite_0_0 || ORIG_REF_NAME==design_1_QSPI_Master_AXI4_Lite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_I2C_Master_AXI4_Lite_0_0/design_1_I2C_Master_AXI4_Lite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_I2C_Master_AXI4_Lite_0_0 || ORIG_REF_NAME==design_1_I2C_Master_AXI4_Lite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Timer_module_0_0/design_1_Timer_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Timer_module_0_0 || ORIG_REF_NAME==design_1_Timer_module_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_0 || ORIG_REF_NAME==design_1_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Instr_Splitter_0_0/design_1_Instr_Splitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Instr_Splitter_0_0 || ORIG_REF_NAME==design_1_Instr_Splitter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_2_0/design_1_axi_bram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_2_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_2_0/design_1_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_2_0 || ORIG_REF_NAME==design_1_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_3_0/design_1_axi_bram_ctrl_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_3_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Timer_module_1_0/design_1_Timer_module_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Timer_module_1_0 || ORIG_REF_NAME==design_1_Timer_module_1_0} -quiet] -quiet

# XDC: c:/Users/deniz/Documents/TEKNOFEST_Modules/birlestirme_denemesi/birlestirme_denemesi.gen/sources_1/bd/design_1/design_1_ooc.xdc
