#!/usr/bin/env python3
"""Re-characterize the project SRAM SPICE views with a pinned OpenRAM/ngspice.

The matching 1 KiB TT pilot is intentionally a separate phase.  The 2 KiB phases
refuse to start until a reviewed pilot acceptance marker is supplied.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

from compare_sram_liberty import compare as compare_liberty


ASIC_DIR = Path(__file__).resolve().parent.parent
OPENRAM_URL = "https://github.com/VLSIDA/OpenRAM.git"
OPENRAM_VERSION = "v1.2.48"
OPENRAM_COMMIT = "b6a6f12642df6b84facc24a77f9a6f67a0d62dab"
NIXPKGS_REV = "b3aad468604d3e488d627c0b43984eb60e75e782"
PDK_VERSION = "8afc8346a57fe1ab7934ba5a6056ea8b43078e71"
DEFAULT_PDK_ROOT = Path.home() / ".ciel/ciel/sky130/versions" / PDK_VERSION

PILOT_MACRO = "sky130_sram_1kbyte_1rw1r_32x256_8"
TARGET_MACRO = "sky130_sram_2kbyte_1rw1r_32x512_8"

# These reproduce the OpenRAM/PDK 3x3 axes exactly:
# slew = scale * 0.005 ns, load = scale * 6.89 fF.
BASELINE_SLEW_SCALES = [0.25, 1, 8]
BASELINE_LOAD_SCALES = [0.25, 1, 4]

# DDK-approved PnR optimization grid for A2.  These result in
# 0.00125..1.5 ns slew and 0.0017225..0.3 pF load axes.
EXPANDED_SLEW_SCALES = [0.25, 1, 4, 16, 64, 160, 300]
EXPANDED_LOAD_SCALES = [0.25, 1, 4, 8.7082728592, 17.4165457184,
                        29.0275761974, 43.5413642961]

PHASES = {
    "pilot": {
        "macro": PILOT_MACRO,
        "words": 256,
        # The similarly named sram_1rw1r_32_256_8_sky130 SS/FF files are a
        # different physical design and are not valid pilot references.
        "corners": [("TT", 1.8, 25)],
    },
    "a1": {
        "macro": TARGET_MACRO,
        "words": 512,
        "corners": [("SS", 1.60, 100), ("TT", 1.80, 25), ("FF", 1.95, -40)],
    },
    "a2": {
        "macro": TARGET_MACRO,
        "words": 512,
        "corners": [("SS", 1.60, 100), ("TT", 1.80, 25), ("FF", 1.95, -40)],
    },
}


def run_checked(cmd: list[str], **kwargs) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=True, text=True, **kwargs)


def ensure_openram(path: Path) -> None:
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        run_checked(["git", "clone", "--filter=blob:none", OPENRAM_URL, str(path)])
    actual = subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True
    ).strip()
    if actual != OPENRAM_COMMIT:
        run_checked(["git", "-C", str(path), "fetch", "origin", OPENRAM_COMMIT])
        run_checked(["git", "-C", str(path), "checkout", "--detach", OPENRAM_COMMIT])
    actual = subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True
    ).strip()
    if actual != OPENRAM_COMMIT:
        raise RuntimeError(f"OpenRAM commit mismatch: {actual} != {OPENRAM_COMMIT}")


def nix_expression() -> str:
    return (
        f'let pkgs = (builtins.getFlake "github:NixOS/nixpkgs/{NIXPKGS_REV}")'
        ".legacyPackages.x86_64-linux; "
        "in [ pkgs.ngspice "
        "(pkgs.python3.withPackages (ps: with ps; [ numpy scipy scikit-learn ])) ]"
    )


def config_text(macro: str, words: int, corner: tuple[str, float, int],
                expanded: bool, output_dir: Path, temp_dir: Path,
                width: float, height: float, initial_period: float,
                guard_period: float, feasibility_only: bool) -> str:
    process, voltage, temperature = corner
    slew_scales = EXPANDED_SLEW_SCALES if expanded else BASELINE_SLEW_SCALES
    load_scales = EXPANDED_LOAD_SCALES if expanded else BASELINE_LOAD_SCALES
    return f'''# Generated by scripts/recharacterize_sram.py; do not hand-edit.
word_size = 32
num_words = {words}
write_size = 8
num_banks = 1
words_per_row = 2
num_rw_ports = 1
num_r_ports = 1
num_w_ports = 0

tech_name = "sky130"
output_name = "{macro}"
output_path = {str(output_dir) + os.sep!r}
openram_temp = {str(temp_dir) + os.sep!r}
existing_sram_width = {width!r}
existing_sram_height = {height!r}

analytical_delay = False
spice_name = "ngspice"
use_conda = False
keep_temp = True
check_lvsdrc = False

use_specified_corners = [({process!r}, {voltage!r}, {temperature!r})]
only_use_config_corners = True
process_corners = [{process!r}]
supply_voltages = [{voltage!r}]
temperatures = [{temperature!r}]
slew_scales = {slew_scales!r}
load_scales = {load_scales!r}

# The matching PDK TT Liberty reports a 1.791 ns minimum period.  Starting at
# 1 ns exercises normal feasibility doubling to 2 ns, then the independent
# minimum-period search, without paying for the upstream 10 ns starting point.
# Unknown 2 KiB PVTs get a looser functional/probe guard.
existing_sram_initial_period = {initial_period!r}
existing_sram_functional_guard_period = {guard_period!r}
existing_sram_feasibility_only = {feasibility_only!r}
'''


def validate_acceptance(path: Path | None) -> None:
    if path is None:
        raise SystemExit(
            "2 KiB characterization is gated: pass --pilot-acceptance to a reviewed "
            "JSON marker whose accepted field is true"
        )
    data = json.loads(path.read_text())
    if data.get("accepted") is not True:
        raise SystemExit(f"pilot acceptance marker is not accepted: {path}")
    if data.get("openram_commit") != OPENRAM_COMMIT:
        raise SystemExit("pilot marker was produced with a different OpenRAM commit")
    if data.get("corners", []) != ["TT_1p8V_25C"]:
        raise SystemExit("pilot marker does not cover the matching official TT corner")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--phase", choices=PHASES, required=True)
    ap.add_argument("--expanded-grid", action="store_true",
                    help="enable the DDK-approved 7x7 PnR-optimization grid")
    ap.add_argument("--pilot-acceptance", type=Path,
                    help="reviewed acceptance marker required before any 2 KiB run")
    ap.add_argument("--parallel-corners", type=int, default=1,
                    help="number of simultaneous corner processes")
    ap.add_argument("--sim-threads", type=int, default=4,
                    help="ngspice threads per corner")
    ap.add_argument("--untrimmed", action="store_true",
                    help="disable standard row/column timing trimming (very slow)")
    ap.add_argument("--feasibility-only", action="store_true",
                    help="run exactly one functional timing simulation, then stop")
    ap.add_argument("--initial-period", type=float,
                    help="override the first feasibility period in ns")
    ap.add_argument("--openram-dir", type=Path,
                    default=ASIC_DIR / "run/lib_characterization/tools/OpenRAM")
    ap.add_argument("--pdk-root", type=Path,
                    default=Path(os.environ.get("PDK_ROOT", DEFAULT_PDK_ROOT)))
    args = ap.parse_args()

    if args.parallel_corners < 1 or args.sim_threads < 1:
        ap.error("thread/process counts must be positive")
    if args.initial_period is not None and args.initial_period <= 0:
        ap.error("--initial-period must be positive")
    if args.phase == "pilot" and args.expanded_grid:
        ap.error("pilot must reproduce the official 3x3 grid")
    if args.phase == "a2" and not args.expanded_grid:
        ap.error("A2 is defined as the expanded-grid experiment; add --expanded-grid")
    if args.phase == "a1" and args.expanded_grid:
        ap.error("A1 must preserve the official 3x3 grid")
    if args.phase != "pilot":
        validate_acceptance(args.pilot_acceptance)

    phase = PHASES[args.phase]
    macro = phase["macro"]
    spice = ASIC_DIR / "macros" / macro / "spice" / f"{macro}.spice"
    model = args.pdk_root / "sky130A/libs.tech/ngspice/sky130.lib.spice"
    if not spice.is_file():
        ap.error(f"SPICE view not found: {spice}")
    if not model.is_file():
        ap.error(f"PDK ngspice model not found: {model}")

    lef = ASIC_DIR / "macros" / macro / "lef" / f"{macro}.lef"
    size_match = None
    if lef.is_file():
        import re
        size_match = re.search(r"^\s*SIZE\s+([0-9.]+)\s+BY\s+([0-9.]+)\s*;",
                               lef.read_text(), re.MULTILINE)
    if size_match is None:
        ap.error(f"cannot read macro dimensions from LEF: {lef}")
    width, height = map(float, size_match.groups())

    ensure_openram(args.openram_dir)
    tag = f"{args.phase}_{'7x7' if args.expanded_grid else '3x3'}"
    if args.feasibility_only:
        period_label = str(args.initial_period if args.initial_period is not None else 1.0).replace(".", "p")
        tag += f"_probe_{period_label}ns"
    out_dir = ASIC_DIR / "macros" / macro / "lib_recharacterized" / tag
    work_dir = ASIC_DIR / "run/lib_characterization" / tag
    log_dir = ASIC_DIR / "reports/sram_characterization/logs" / tag
    config_dir = ASIC_DIR / "reports/sram_characterization/configs" / tag
    for directory in (out_dir, work_dir, log_dir, config_dir):
        directory.mkdir(parents=True, exist_ok=True)

    # OpenRAM v1.2.48 unconditionally sources $CONDA_HOME/bin/activate around
    # each SPICE invocation, even when use_conda=False.  Supply a no-op shim so
    # the pinned Nix ngspice remains selected and OpenRAM does not bootstrap a
    # second, mutable tool environment.
    conda_shim = work_dir / "conda_shim/bin"
    conda_shim.mkdir(parents=True, exist_ok=True)
    (conda_shim / "activate").write_text("conda() { return 0; }\nexport -f conda\n")

    env = os.environ.copy()
    env.update({
        "PDK_ROOT": str(args.pdk_root),
        "OPENRAM_HOME": str(args.openram_dir / "compiler"),
        "OPENRAM_TECH": str(args.openram_dir / "technology"),
        "PYTHONPATH": str(args.openram_dir / "compiler"),
        "CONDA_HOME": str(conda_shim.parent),
    })

    jobs = []
    started = dt.datetime.now(dt.timezone.utc)
    initial_period = args.initial_period if args.initial_period is not None else 1.0
    default_guard = 2.0 if macro == PILOT_MACRO else 8.0
    guard_period = max(default_guard, initial_period)
    for process, voltage, temperature in phase["corners"]:
        corner_name = f"{process}_{str(voltage).replace('.', 'p')}V_{str(temperature).replace('-', 'n')}C"
        corner_temp = work_dir / corner_name
        if corner_temp.exists():
            shutil.rmtree(corner_temp)
        corner_temp.mkdir(parents=True, exist_ok=True)
        corner_output = corner_temp / "output"
        corner_output.mkdir(parents=True, exist_ok=True)
        cfg = config_dir / f"{corner_name}.py"
        cfg.write_text(config_text(macro, phase["words"],
                                   (process, voltage, temperature),
                                   args.expanded_grid, corner_output, corner_temp,
                                   width, height, initial_period, guard_period,
                                   args.feasibility_only))
        log_path = log_dir / f"{corner_name}.log"
        log_handle = log_path.open("w")
        cmd = [
            "nix", "shell", "--impure", "--expr", nix_expression(), "--command",
            "python3", str(ASIC_DIR / "scripts/openram_existing_sram_char.py"),
            "-s", "ngspice", "-m", str(args.sim_threads), "-k",
        ]
        if args.untrimmed:
            cmd.append("-r")
        cmd.extend([str(cfg), str(spice)])
        jobs.append((corner_name, cmd, log_path, log_handle, corner_output))

    active: list[tuple[str, subprocess.Popen[str], Path, object, Path]] = []
    pending = list(jobs)
    failures = []
    while pending or active:
        while pending and len(active) < args.parallel_corners:
            name, cmd, log_path, handle, corner_output = pending.pop(0)
            print(f"[{name}] starting; log={log_path}", flush=True)
            handle.write("COMMAND: " + " ".join(cmd) + "\n")
            handle.write(f"OPENRAM_COMMIT: {OPENRAM_COMMIT}\nPDK_VERSION: {PDK_VERSION}\n")
            handle.flush()
            proc = subprocess.Popen(cmd, cwd=ASIC_DIR, env=env,
                                    stdout=handle, stderr=subprocess.STDOUT, text=True)
            active.append((name, proc, log_path, handle, corner_output))
        name, proc, log_path, handle, corner_output = active.pop(0)
        rc = proc.wait()
        handle.close()
        staged_lib = corner_output / f"{macro}_{name}.lib"
        feasibility_marker = corner_output / "feasibility_passed.json"
        expected_output = feasibility_marker if args.feasibility_only else staged_lib
        if rc == 0 and (not expected_output.is_file() or expected_output.stat().st_size == 0):
            print(f"[{name}] missing or empty staged output: {expected_output}", file=sys.stderr)
            rc = 2
        if rc == 0:
            if args.feasibility_only:
                published_marker = out_dir / f"{name}_feasibility_passed.json"
                publish_temp = out_dir / f".{published_marker.name}.tmp"
                shutil.copy2(feasibility_marker, publish_temp)
                publish_temp.replace(published_marker)
            else:
                # Publish only a complete, nonempty Liberty.  Interrupted runs
                # can therefore never overwrite the last reviewed result with
                # a zero-byte file.
                published_lib = out_dir / staged_lib.name
                publish_temp = out_dir / f".{staged_lib.name}.tmp"
                shutil.copy2(staged_lib, publish_temp)
                publish_temp.replace(published_lib)
        print(f"[{name}] exit={rc}", flush=True)
        if rc:
            failures.append((name, rc, log_path))

    comparisons = []
    if not failures and args.phase == "pilot" and not args.feasibility_only:
        comparison_dir = ASIC_DIR / "reports/sram_characterization/comparisons" / tag
        comparison_dir.mkdir(parents=True, exist_ok=True)
        official_dir = args.pdk_root / "sky130A/libs.ref/sky130_sram_macros/lib"
        for process, voltage, temperature in phase["corners"]:
            corner_name = f"{process}_{str(voltage).replace('.', 'p')}V_{str(temperature).replace('-', 'n')}C"
            reference = official_dir / f"{PILOT_MACRO}_{corner_name}.lib"
            candidate = out_dir / f"{macro}_{corner_name}.lib"
            if not reference.is_file():
                failures.append((corner_name, 3, reference))
                continue
            result = compare_liberty(reference, candidate)
            report_path = comparison_dir / f"{corner_name}.json"
            report_path.write_text(json.dumps(result, indent=2, allow_nan=False) + "\n")
            summary = result["all_points"]
            comparisons.append({
                "corner": corner_name,
                "reference": str(reference),
                "candidate": str(candidate.relative_to(ASIC_DIR)),
                "report": str(report_path.relative_to(ASIC_DIR)),
                "axes_equal": result["axes_equal"],
                "structural_match": result["structural_match"],
                "arc_tables": result["matched_arc_tables"],
                "points": summary["count"],
                "mean_percent_difference": summary["mean_percent_difference"],
                "max_percent_difference": summary["max_percent_difference"],
            })
            if not result["axes_equal"] or not result["structural_match"]:
                failures.append((corner_name, 4, report_path))

    metadata = {
        "phase": args.phase,
        "macro": macro,
        "grid": "7x7" if args.expanded_grid else "3x3",
        "corners": phase["corners"],
        "openram_version": OPENRAM_VERSION,
        "openram_commit": OPENRAM_COMMIT,
        "nixpkgs_revision": NIXPKGS_REV,
        "pdk_version": PDK_VERSION,
        "source_spice": str(spice.relative_to(ASIC_DIR)),
        "trim_netlist": not args.untrimmed,
        "feasibility_only": args.feasibility_only,
        "initial_period_ns": initial_period,
        "parallel_corners": args.parallel_corners,
        "sim_threads_per_corner": args.sim_threads,
        "started_utc": started.isoformat(),
        "finished_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "pilot_comparisons": comparisons,
        "failures": [{
            "corner": n,
            "returncode": rc,
            "log": str(p.relative_to(ASIC_DIR)) if p.is_relative_to(ASIC_DIR) else str(p),
        }
                     for n, rc, p in failures],
    }
    (out_dir / "run_metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    if failures:
        for name, rc, path in failures:
            print(f"FAILED {name} ({rc}): {path}", file=sys.stderr)
        return 1
    print(f"Characterization complete: {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
